title: OpenFoxBlog
description: "Fuer alle, die Privatsphaere und Sicherheit schaetzen"
author:
  name: "Damon Leven"
  email: "mcwertgaming@gmail.com"
  url: "Placeholder"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Damon Leven"
year : "2020"
